from detail_interface import *

class StudentDetail(DetailGUI):
    def __init__(self):
        super().__init__()
        self.label_title["text"] = "教师基本信息明细"
        self.style02.configure("TLabel",font=("微软雅黑",12),foreground="Navy")
        self.style02.configure("TRadiobutton",font=("微软雅黑",10))
        self.label_tid = Label(self.pane_detail,text="教师编号：")
        self.label_tid.place(x=103,y=20)
        self.entry_tid = Entry(self.pane_detail,font=("微软雅黑",12),background="black",width=20)
        self.entry_tid.place(x=188,y=19)
        self.label_name = Label(self.pane_detail, text="姓名：")
        self.label_name.place(x=135, y=50)
        self.entry_name = Entry(self.pane_detail, font=("微软雅黑", 12), background="black", width=20)
        self.entry_name.place(x=188, y=49)
        self.label_gender = Label(self.pane_detail, text="性别：")
        self.label_gender.place(x=135, y=80)
        self.label_gender = IntVar()
        self.Radio_men = Radiobutton(self.pane_detail, text="男",variable=self.label_gender,value=1)
        self.Radio_men.place(x=188, y=80)
        self.Radio_women = Radiobutton(self.pane_detail, text="女", variable=self.label_gender, value=2)
        self.Radio_women.place(x=224, y=80)
        self.label_birthday = Label(self.pane_detail, text="出生日期：")
        self.label_birthday.place(x=103, y=110)
        self.entry_birthday = Entry(self.pane_detail, font=("微软雅黑", 12), background="black", width=20)
        self.entry_birthday.place(x=188, y=109)
        self.label_phone = Label(self.pane_detail, text="电话号码：")
        self.label_phone.place(x=103, y=140)
        self.entry_phone = Entry(self.pane_detail, font=("微软雅黑", 12), background="black", width=20)
        self.entry_phone.place(x=188, y=139)
        self.label_email = Label(self.pane_detail, text="邮箱地址：")
        self.label_email.place(x=103, y=170)
        self.entry_email = Entry(self.pane_detail, font=("微软雅黑", 12), background="black", width=20)
        self.entry_email.place(x=188, y=169)
        self.label_professional = Label(self.pane_detail, text="职称：")
        self.label_professional.place(x=135, y=200)
        self.entry_professional = Entry(self.pane_detail, font=("微软雅黑", 12), background="black", width=20)
        self.entry_professional.place(x=188, y=199)
        self.label_college = Label(self.pane_detail, text="毕业院校：")
        self.label_college.place(x=103, y=230)
        self.entry_college = Entry(self.pane_detail, font=("微软雅黑", 12), background="black", width=20)
        self.entry_college.place(x=188, y=229)
        self.label_induction = Label(self.pane_detail, text="入职时间：")
        self.label_induction.place(x=103, y=260)
        self.entry_induction = Entry(self.pane_detail, font=("微软雅黑", 12), background="black", width=20)
        self.entry_induction.place(x=188, y=259)


if __name__ == "__main__":
    student = StudentDetail()
    student.mainloop()